### ISSUE TITLE
delete returns SignerDoesNotExist, but transaction hash on explorer shows success

### ISSUE THREAD

**Issue by isoldo** [near/near-cli#1012]
**Describe the bug**
CLI returned an error (SignerDoesNotExist), and the explorer shows that the transaction succeeded.
When trying to create a new account with the same name, creation succeeds meaning the account was actually deleted.
[https://explorer.testnet.near.org/transactions/EXuXxPT2JDVLaXc91jeFfdFYU9XM4gF3oAE7ufg7rRCL](url)
[https://explorer.testnet.near.org/transactions/AReUBYzad8rHSFoJDLpeVWzmCzkN4SiAaxGJimRbepGe](url)

**To Reproduce**
Happend twice in many `near delete` scenarios, not sure how reproducible it is.
It was called in a bash script which first funded the account:
```
near send iso18.testnet lc3.iso18.testnet
near delete lc3.iso18.testnet iso18.testnet
```

**Expected behavior**
CLI should report success.

**Screenshots**
![image](https://user-images.githubusercontent.com/13051245/183917538-8adad4dd-f28c-476f-9ed4-45765f31165e.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 12.4 (Monterey)

**Additional context**
[near_cli_error.txt](https://github.com/near/near-cli/files/9300571/near_cli_error.txt)

`near --version` returns `3.3.1`

**Comment by isoldo** [comment]
@chefsale FYI

**Comment by pablojorge** [comment]
Same here, but using _just_ `near-api-js`:

Full dump of the tx:

```
Actions: [
  Action {
    deleteAccount: DeleteAccount {
      beneficiaryId: 'b2fe6f7aa4ddea6759b28ac0707e6a51b073fd9583ff9a84553a5989817cb48b'
    },
    enum: 'deleteAccount'
  }
]
Transaction {
  signerId: 'd4eaca26307539136895ffb0977017a5ec6b7250ef56f79f83ea261e79e01499',
  publicKey: PublicKey {
    keyType: 0,
    data: <Buffer d4 ea ca 26 30 75 39 13 68 95 ff b0 97 70 17 a5 ec 6b 72 50 ef 56 f7 9f 83 ea 26 1e 79 e0 14 99>
  },
  nonce: 61531709000040,
  receiverId: 'd4eaca26307539136895ffb0977017a5ec6b7250ef56f79f83ea261e79e01499',
  actions: [ Action { deleteAccount: [DeleteAccount], enum: 'deleteAccount' } ],
  blockHash: <Buffer 39 1a dc d8 65 28 16 97 33 81 9a 81 83 f0 eb 70 39 11 41 a6 84 ec 33 67 e1 e8 f7 37 81 36 6e 06>
}
Tx hash: 0x1bdebfe3ece17f0cc39c251b3aca269b84bf7929b4c48eb030825a116d5a4674
SignedTransaction {
  transaction: Transaction {
    signerId: 'd4eaca26307539136895ffb0977017a5ec6b7250ef56f79f83ea261e79e01499',
    publicKey: PublicKey {
      keyType: 0,
      data: <Buffer d4 ea ca 26 30 75 39 13 68 95 ff b0 97 70 17 a5 ec 6b 72 50 ef 56 f7 9f 83 ea 26 1e 79 e0 14 99>
    },
    nonce: 61531709000040,
    receiverId: 'd4eaca26307539136895ffb0977017a5ec6b7250ef56f79f83ea261e79e01499',
    actions: [ [Action] ],
    blockHash: <Buffer 39 1a dc d8 65 28 16 97 33 81 9a 81 83 f0 eb 70 39 11 41 a6 84 ec 33 67 e1 e8 f7 37 81 36 6e 06>
  },
  signature: Signature {
    keyType: 0,
    data: [
        2,  29,  92, 245, 163, 164,   0,  64,  15, 223,  51,
      228, 201,  38, 219,   9,   0, 156, 198, 136, 246, 205,
       37, 212, 130,  10, 172, 195, 104, 140, 127, 213, 142,
       48, 249, 124, 143, 147,  81, 102, 121,  80, 173,   9,
      222, 201,   8, 124, 191, 110,  50,   4,  87, 174, 233,
       48, 165,   9, 230, 236,  14, 198,  49,  12
    ]
  }
}

*** Serialized TX: 400000006434656163613236333037353339313336383935666662303937373031376135656336623732353065663536663739663833656132363165373965303134393900d4eaca26307539136895ffb0977017a5ec6b7250ef56f79f83ea261e79e014996849a877f63700004000000064346561636132363330373533393133363839356666623039373730313761356563366237323530656635366637396638336561323631653739653031343939391adcd86528169733819a8183f0eb70391141a684ec3367e1e8f73781366e060100000007400000006232666536663761613464646561363735396232386163303730376536613531623037336664393538336666396138343535336135393839383137636234386200021d5cf5a3a400400fdf33e4c926db09009cc688f6cd25d4820aacc3688c7fd58e30f97c8f9351667950ad09dec9087cbf6e320457aee930a509e6ec0ec6310c ***
```

When broadcasting the above, I get the following error:

```
SignerDoesNotExist [Error]: Signer d4eaca26307539136895ffb0977017a5ec6b7250ef56f79f83ea261e79e01499 does not exist
    at Object.parseRpcError (.../near/node_modules/near-api-js/lib/utils/rpc_errors.js:38:19)
    at JsonRpcProvider.sendJsonRpc (.../near/node_modules/near-api-js/lib/providers/json-rpc-provider.js:147:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async broadcast (.../near/main.js:259:20)
    at async Object.handleBroadcast [as handler] (.../near/main.js:183:3) {
  type: 'SignerDoesNotExist',
  context: undefined,
  signer_id: 'd4eaca26307539136895ffb0977017a5ec6b7250ef56f79f83ea261e79e01499'
}
```

But in fact the transaction was executed successfully: https://explorer.mainnet.near.org/transactions/2so1WEW8AX8xdKSPVzX7wwXYKHAbNxGp67sWwjReEMDM
