### ISSUE TITLE
Error 500 from Json RPC is not parsed

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#316]
When action receives error 500, the output to the user is unclear:
 ```
 Starting deployment. Account id: delegate-to-me.test, node: [https://rpc.betanet.nearprotocol.com](https://rpc.betanet.nearprotocol.com), helper: [https://helper.betanet.nearprotocol.com](https://helper.betanet.nearprotocol.com), file: projects/nearprotocol/staking-contract/res/staking_contract.wasm
 Error: InternalServerError: <html>
 <head><title>500 Internal Server Error</title></head>
 <body bgcolor="white">
 <center><h1>500 Internal Server Error</h1></center>
 <hr><center>nginx/1.14.0 (Ubuntu)</center>
 </body>
 </html>

 at Object.fetchJson (/usr/local/lib/node_modules/near-shell/node_modules/near-api-js/lib/utils/web.js:46:36)
 at processTicksAndRejections (internal/process/task_queues.js:94:5)
 at async JsonRpcProvider.sendJsonRpc (/usr/local/lib/node_modules/near-shell/node_modules/near-api-js/lib/providers/json-rpc-provider.js:96:26)
 at async Account.signAndSendTransaction (/usr/local/lib/node_modules/near-shell/node_modules/near-api-js/lib/account.js:96:22)
 at async exports.deploy (/usr/local/lib/node_modules/near-shell/index.js:36:5)
 at async Object.handler (/usr/local/lib/node_modules/near-shell/utils/exit-on-error.js:4:9) 

 { message: '<html>\r\n' + '<head><title>500 Internal Server Error</title></head>\r\n' + '<body bgcolor="white">\r\n' + '<center><h1>500 Internal Server Error</h1></center>\r\n' + '<hr><center>nginx/1.14.0 (Ubuntu)</center>\r\n' + '</body>\r\n' + '</html>\r\n' } 

```

**Comment by june07** [comment]
What was the command line that was run?
