### ISSUE TITLE
Running generate-key with useLedgerKey fails with module not found

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#396]
```
 $ near --version 
 0.24.1

$ near generate-key multisig3 --useLedgerKey
 ...
 Error: Cannot find module '@ledgerhq/hw-transport-node-hid'
 Require stack:

*   /usr/local/lib/node_modules/near-shell/middleware/ledger.js
*   /usr/local/lib/node_modules/near-shell/bin/near-cli.js
*   /usr/local/lib/node_modules/near-shell/bin/near
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
     at Module.require (internal/modules/cjs/loader.js:848:19)
     at require (internal/modules/cjs/helpers.js:74:18)
     at useLedgerSigner (/usr/local/lib/node_modules/near-shell/middleware/ledger.js:12:43)
     at /usr/local/lib/node_modules/near-shell/node_modules/yargs/lib/middleware.js:50:38
     at processTicksAndRejections (internal/process/task_queues.js:94:5) { code: 'MODULE_NOT_FOUND', requireStack: [ '/usr/local/lib/node_modules/near-shell/middleware/ledger.js', '/usr/local/lib/node_modules/near-shell/bin/near-cli.js', '/usr/local/lib/node_modules/near-shell/bin/near' ] } 

    ```

Near installation failures:
 ```
 prebuild-install WARN install EACCES: permission denied, access '/Users/cypress/.npm'
 gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/Users/cypress/Library/Caches/node-gyp/12.14.1"
 gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/near-shell/node_modules/usb/.node-gyp"
 gyp WARN install got an error, rolling back install
 gyp WARN install got an error, rolling back install
 gyp ERR! configure error
 gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/usb/.node-gyp'
 gyp ERR! System Darwin 19.5.0
 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
 gyp ERR! cwd /usr/local/lib/node_modules/near-shell/node_modules/usb
 gyp ERR! node -v v12.14.1
 gyp ERR! node-gyp -v v5.1.0
 gyp ERR! not ok
 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-hid@1.2.0 (node_modules/near-shell/node_modules/node-hid):
 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-hid@1.2.0 install: `prebuild-install || node-gyp rebuild`
 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 (node_modules/near-shell/node_modules/usb):
 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 install: `prebuild-install --verbose || node-gyp rebuild`
 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
 ```

**Comment by vgrichina** [comment]
@ilblackdragon looks like issue with file system permissions:

> prebuild-install WARN install EACCES: permission denied, access '/Users/cypress/.npm'

> gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/near-shell/node_modules/usb/.node-gyp'

so you need to make sure these are writable, etc

on near-shell side the best we can do is to give more specific error than `Error: Cannot find module '@ledgerhq/hw-transport-node-hid'`

**Comment by ilblackdragon** [comment]
The current fix:
1. Change permissions on /usr/local to your users with `chown -R <username> /usr/local`
2. Install directly this module without sudo: `npm install -g @ledgerhq/hw-transport-node-hid`
