### ISSUE TITLE
Not opening app leads to CLA not supported error

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-cli#409]
near-shell version 0.24.2

1\. Unlock Ledger but don't open NEAR app.
 2\. Run:
 ```
 $ near generate-key test123 --useLedgerKey
 Using options: 

 { useLedgerKey: "44'/397'/0'/0'/1'", networkId: 'default', nodeUrl: 'https://rpc.testnet.near.org', contractName: undefined, walletUrl: 'https://wallet.testnet.near.org', helperUrl: 'https://helper.testnet.near.org', accountId: 'test123', initialBalance: null } 

Make sure to connect your Ledger and open NEAR app
 Waiting for confirmation on Ledger...
 Error: Error
 at new TransportStatusError (/usr/local/lib/node_modules/@ledgerhq/hw-transport-node-hid/node_modules/@ledgerhq/errors/dist/index.cjs.js:288:18)
 at TransportNodeHid.Transport.send (/usr/local/lib/node_modules/@ledgerhq/hw-transport-node-hid/node_modules/@ledgerhq/hw-transport/lib/Transport.js:59:15)
 at async Object.getPublicKey (/usr/local/lib/node_modules/near-ledger-js/index.js:31:30)
 at async getPublicKeyForPath (/usr/local/lib/node_modules/near-shell/middleware/ledger.js:26:30)
 at async /usr/local/lib/node_modules/near-shell/commands/generate-key.js:18:35
 at async Object.handler (/usr/local/lib/node_modules/near-shell/utils/exit-on-error.js:4:9) 

 { name: 'TransportStatusError', message: 'Ledger device: CLA_NOT_SUPPORTED (0x6e00)', stack: 'Error\n' + ' at new TransportStatusError (/usr/local/lib/node_modules/@ledgerhq/hw-transport-node-hid/node_modules/@ledgerhq/errors/dist/index.cjs.js:288:18)\n' + ' at TransportNodeHid.Transport.send (/usr/local/lib/node_modules/@ledgerhq/hw-transport-node-hid/node_modules/@ledgerhq/hw-transport/lib/Transport.js:59:15)\n' + ' at async Object.getPublicKey (/usr/local/lib/node_modules/near-ledger-js/index.js:31:30)\n' + ' at async getPublicKeyForPath (/usr/local/lib/node_modules/near-shell/middleware/ledger.js:26:30)\n' + ' at async /usr/local/lib/node_modules/near-shell/commands/generate-key.js:18:35\n' + ' at async Object.handler (/usr/local/lib/node_modules/near-shell/utils/exit-on-error.js:4:9)', statusCode: 28160, statusText: 'CLA_NOT_SUPPORTED' } 

```

**Comment by vgrichina** [comment]
It says `Make sure to connect your Ledger and open NEAR app`, so assigning P3 unless there are any objections.
