### ISSUE TITLE
Failing to run near-cli to obtain a public key for my Ledger wallet

### ISSUE THREAD

**Issue by mrkimchi** [near/near-cli#545]
***Describe the bug***
 Unable to run near-cli to obtain a public key for my Ledger wallet

***To Reproduce***
 ```laptop@top:~$ near generate-key key --useLedgerKey
 near generate-key <span class="error">[account-id]</span>

generate key or show key from Ledger

Options:
 --help Show help <span class="error">[boolean]</span>
 --version Show version number <span class="error">[boolean]</span>
 --nodeUrl, --node_url NEAR node URL <span class="error">[string]</span> <span class="error">[default: "https://rpc.testnet.near.org"]</span>
 --networkId, --network_id NEAR network ID, allows using different keys based on network <span class="error">[string]</span> <span class="error">[default: "default"]</span>
 --helperUrl NEAR contract helper URL <span class="error">[string]</span>
 --keyPath Path to master account key <span class="error">[string]</span>
 --accountId, --account_id Unique identifier for the account <span class="error">[string]</span>
 --useLedgerKey Use Ledger for signing with given HD key path <span class="error">[string]</span> <span class="error">[default: "44'/397'/0'/0'/1'"]</span>
 --seedPhrase Seed phrase mnemonic <span class="error">[string]</span>
 --seedPath HD path derivation <span class="error">[string]</span> <span class="error">[default: "m/44'/397'/0'"]</span>
 --walletUrl Website for NEAR Wallet <span class="error">[string]</span>
 --contractName Account name of contract <span class="error">[string]</span>
 --masterAccount Master account used when creating new accounts <span class="error">[string]</span>
 --helperAccount Expected top-level account for a network <span class="error">[string]</span>
 --verbose, -v Prints out verbose output <span class="error">[boolean]</span> <span class="error">[default: false]</span>

Error: Cannot find module '@ledgerhq/hw-transport-node-hid'
 Require stack:

*   /usr/local/lib/node_modules/near-cli/middleware/ledger.js
*   /usr/local/lib/node_modules/near-cli/bin/near-cli.js
*   /usr/local/lib/node_modules/near-cli/bin/near
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
     at Function.Module._load (internal/modules/cjs/loader.js:686:27)
     at Module.require (internal/modules/cjs/loader.js:848:19)
     at require (internal/modules/cjs/helpers.js:74:18)
     at useLedgerSigner (/usr/local/lib/node_modules/near-cli/middleware/ledger.js:12:43)
     at /usr/local/lib/node_modules/near-cli/node_modules/yargs/build/lib/middleware.js:44:62
     at processTicksAndRejections (internal/process/task_queues.js:94:5) { code: 'MODULE_NOT_FOUND', requireStack: [ '/usr/local/lib/node_modules/near-cli/middleware/ledger.js', '/usr/local/lib/node_modules/near-cli/bin/near-cli.js', '/usr/local/lib/node_modules/near-cli/bin/near' ] } 

    ```

***Expected behavior***
 Following this tutorial I should be able to run near-cli to create my public key. [https://docs.near.org/docs/tokens/token-custody#cli-recommended-for-developers-and-validators](https://docs.near.org/docs/tokens/token-custody#cli-recommended-for-developers-and-validators)

***Desktop (please complete the following information):***

*   OS: Ubuntu 18.04.5 LTS
*   near --version 1.1.0
*   @ledgerhq/hw-transport-node-hid 5.25.0 (installed through [https://www.npmjs.com/package/@ledgerhq/hw-transport-node-hid](https://www.npmjs.com/package/@ledgerhq/hw-transport-node-hid))
*   Ledger Wallet X, near version 1.1.3

***Additional context***
 It's my preferable option to generate the public key requested by the NEAR Foundation to claim my NEAR tokens. Thank you in advance.

**Comment by ilblackdragon** [comment]
Usually, this is issue with old node.
You want to switch to node v12 and reinstall near-cli

**Comment by mrkimchi** [comment]
Sorry I forgot to mention.

nvm version v12.14.1

**Comment by mrkimchi** [comment]
Trying to run the command with sudo and the verbose is:

```laptop@top:~$ sudo near generate-key --useLedgerKey
/usr/local/lib/node_modules/near-cli/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/near-cli/utils/eventtracking.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

**Comment by mikedotexe** [comment]
@mrkimchi this is very interesting and odd. I see in the stack trace there's `eventtracking.js` and I know the `uuid` module is used there and I doubt it's used in the `generate-key` command. This makes me wonder whether or not it's related to that command. Could you please try running an unrelated command for me?
`near state mike.testnet`
I want to see if the same behavior happens. Thanks so much for reporting

**Comment by ilblackdragon** [comment]
This is really weird error, but it seems like the cause is updating node in place doesn't work very well.
We had someone else report the same error and their fix was to remove all module and nodejs and reinstall again: `rm -rf /usr/local/lib/node_modules/ /usr/lib/node_modules/`

**Comment by mikedotexe** [comment]
Going to see if this issue persists. If we don't see movement here will intend to close in a week or so.

**Comment by alexauroradev** [comment]
Experiencing this same issue too, within a singe shell login. First the command works, then it stops to work with same output
