### ISSUE TITLE
NOT WORKING: < npm install -g near-cli >DEPENDENCY FAILS

### ISSUE THREAD

**Issue by diazMelgarejo** [near/near-cli#550]
**Describe the bug**
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v83-linux-x64.tar.gz

**To Reproduce**
1. fresh installation: `npm install -g near-cli`
2. LO and behold, error getting https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v83-linux-x64.tar.gz

**Expected behavior**
A clear and concise description of what you expected to happen: WILL INSTALL

so i checked https://github.com/tessel/node-usb/releases and there really is no usb-v1.6.3-node-v83 THERE

there's only https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v79-linux-x64.tar.gz

**Desktop (please complete the following information):**
 - OS: latest update of Ubuntu Xenial

```
$ npm install -g near-cli
/home/USER/.npm-global/bin/near -> /home/USER/.npm-global/lib/node_modules/near-cli/bin/near

> node-hid@1.3.0 install /home/USER/.npm-global/lib/node_modules/near-cli/node_modules/node-hid
> prebuild-install || node-gyp rebuild


> usb@1.6.3 install /home/USER/.npm-global/lib/node_modules/near-cli/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.5
prebuild-install info looking for cached prebuild @ /home/USER/.npm/_prebuilds/91abd0-usb-v1.6.3-node-v83-linux-x64.tar.gz
prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v83-linux-x64.tar.gz
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v83-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.12.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/USER/.npm-global/lib/node_modules/near-cli/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
compilation terminated.
libusb.target.mk:150: recipe for target 'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed
make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/home/USER/.npm-global/lib/node_modules/near-cli/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/USER/.npm-global/lib/node_modules/near-cli/node_modules/usb
gyp ERR! node -v v14.12.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 (node_modules/near-cli/node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 install: `prebuild-install --verbose || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ near-cli@1.2.0
added 291 packages from 217 contributors in 206.368s

```

**Comment by diazMelgarejo** [comment]
figured it out, you just lack good documentation on the necessary nodejs/npm installed, we cannot use 13.x or 14.x

we should say **stick to 12.x:** `curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -`

OTHERWISE, the installation will fail, [node-usb](https://github.com/tessel/node-usb) upstream only supports up to v79
