### ISSUE TITLE
Testnet down -- large 500 error from CLI

### ISSUE THREAD

**Issue by TrevorJTClarke** [near/near-cli#607]
***Describe the bug***
 When the testnet (or other?) is down, CLI prints the html error response.

***To Reproduce***
 1\. Use NEAR CLI
 2\. network MUST not be reachable or down
 3\. `$ near state rp1.testnet` (or any similar cmd)

***Expected behavior***
 I would like a smaller error explaining the network connection could not be reached, try again later.

***Screenshots***

*   See sample below

***Desktop (please complete the following information):***

*   OS: <span class="error">[MacOS]</span>
*   Version <span class="error">[10.15.6]</span>

***Additional context***
 Full example response:
 ```
 An error occured
 BadGatewayError:
 <html><head>
 <meta http-equiv="content-type" content="text/html;charset=utf-8">
 <title>502 Server Error</title>
 </head>
 <body text=#000000 bgcolor=#ffffff>
 <h1>Error: Server Error</h1>
 <h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
 <h2></h2>
 </body></html>

 at /.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/web.js:57:44
 at processTicksAndRejections (internal/process/task_queues.js:93:5)
 at async Object.exponentialBackoff <span class="error">[as default]</span> (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
 at async Object.fetchJson (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/web.js:45:22)
 at async JsonRpcProvider.sendJsonRpc (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:138:26)
 at async JsonRpcProvider.query (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:65:24)
 at async Account.fetchState (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:49:23)
 at async Account.state (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:56:9)
 at async Near.account (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/near.js:40:9)
 at async exports.viewAccount (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/index.js:179:19)
 at async Object.handler (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/utils/exit-on-error.js:39:9) 

 { [stack]: 'BadGatewayError: \n' + '<html><head>\n' + '<meta http-equiv="content-type" content="text/html;charset=utf-8">\n' + '<title>502 Server Error</title>\n' + '</head>\n' + '<body text=#000000 bgcolor=#ffffff>\n' + '<h1>Error: Server Error</h1>\n' + '<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n' + '<h2></h2>\n' + '</body></html>\n' + '\n' + ' at /.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/web.js:57:44\n' + ' at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' + ' at async Object.exponentialBackoff [as default] (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)\n' + ' at async Object.fetchJson (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/web.js:45:22)\n' + ' at async JsonRpcProvider.sendJsonRpc (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:138:26)\n' + ' at async JsonRpcProvider.query (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/providers/json-rpc-provider.js:65:24)\n' + ' at async Account.fetchState (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:49:23)\n' + ' at async Account.state (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:56:9)\n' + ' at async Near.account (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/node_modules/near-api-js/lib/near.js:40:9)\n' + ' at async exports.viewAccount (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/index.js:179:19)\n' + ' at async Object.handler (/.nvm/versions/node/v14.15.0/lib/node_modules/near-cli/utils/exit-on-error.js:39:9)', message: '\n' + '<html><head>\n' + '<meta http-equiv="content-type" content="text/html;charset=utf-8">\n' + '<title>502 Server Error</title>\n' + '</head>\n' + '<body text=#000000 bgcolor=#ffffff>\n' + '<h1>Error: Server Error</h1>\n' + '<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>\n' + '<h2></h2>\n' + '</body></html>\n', [name]: 'BadGatewayError', status: 502, statusCode: 502, expose: false } 

```

**Comment by bowenwang1996** [comment]
Sorry about that. We had to do a hard fork. Can you confirm that it works now?

**Comment by TrevorJTClarke** [comment]
@bowenwang1996 yep, testnet is working now, deployed contract successfully. However, reported this so the cli could handle this type of error better? Or maybe its more on the rpc api side?
