### ISSUE TITLE
Generate key from ledger X failed

### ISSUE THREAD

**Issue by biluohc** [near/near-cli#616]
**Describe the bug**
Ledger Live is work(I add a ETH acount success) but generate key from ledger nanoX failed

**To Reproduce**
1. connect ledger
2. open the Near APP in legder
3. run 'NEAR_ENV=mainnet near generate-key --useLedgerKey="m/44'/397'/0'"  -v' 

**Expected behavior**
Generate a key

**Screenshots**
```sh
NEAR_ENV=mainnet near generate-key --useLedgerKey="m/44'/397'/0'"  -v                                                                                                            (757ms)
Using options: {
  useLedgerKey: "m/44'/397'/0'",
  v: true,
  verbose: true,
  networkId: 'mainnet',
  nodeUrl: 'https://rpc.mainnet.near.org',
  contractName: undefined,
  walletUrl: 'https://wallet.near.org',
  helperUrl: 'https://helper.mainnet.near.org',
  helperAccount: 'near',
  explorerUrl: 'https://explorer.mainnet.near.org',
  seedPath: "m/44'/397'/0'",
  initialBalance: null
}
Make sure to connect your Ledger and open NEAR app
near generate-key [account-id]

generate key or show key from Ledger

选项：
      --help                     显示帮助信息  [布尔]
      --version                  显示版本号  [布尔]
      --nodeUrl, --node_url      NEAR node URL  [字符串] [默认值: "https://rpc.mainnet.near.org"]
      --networkId, --network_id  NEAR network ID, allows using different keys based on network  [字符串] [默认值: "mainnet"]
      --helperUrl                NEAR contract helper URL  [字符串]
      --keyPath                  Path to master account key  [字符串]
      --accountId, --account_id  Unique identifier for the account  [字符串]
      --useLedgerKey             Use Ledger for signing with given HD key path  [字符串] [默认值: "44'/397'/0'/0'/1'"]
      --seedPhrase               Seed phrase mnemonic  [字符串]
      --seedPath                 HD path derivation  [字符串] [默认值: "m/44'/397'/0'"]
      --walletUrl                Website for NEAR Wallet  [字符串]
      --contractName             Account name of contract  [字符串]
      --masterAccount            Master account used when creating new accounts  [字符串]
      --helperAccount            Expected top-level account for a network  [字符串]
  -v, --verbose                  Prints out verbose output  [布尔] [默认值: false]

TypeError: cannot open device with path IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS01@14100000/USB2.0 Hub@14100000/AppleUSB20Hub@14100000/AppleUSB20HubPort@14140000/Nano X@14140000/Nano X@0/IOUSBHostHIDDevice@14140000,0
    at new HID (/usr/local/lib/node_modules/near-cli/node_modules/node-hid/nodehid.js:49:17)
    at /usr/local/lib/node_modules/near-cli/node_modules/@ledgerhq/hw-transport-node-hid/lib/TransportNodeHid.js:66:37
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async useLedgerSigner (/usr/local/lib/node_modules/near-cli/middleware/ledger.js:15:23)
    at async Promise.all (index 1)
```

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Version  Leager's NEAR 1.1.3,  near-cli@1.4.0, Node.js v14.7.0

**Additional context**

1. `sudo` got the same error.

**Comment by ilblackdragon** [comment]
@biluohc I don't think you are using correct Ledger HD path.
Try using `--useLedgerKey="44'/397'/0'/0'/1'"`

**Comment by biluohc** [comment]
But `"44'/397'/0'/0'/1'"` is not `"m/44'/397'/0'"`, 
`"m/44'/397'/0'"`is near-cli's default path for seedPhrase, 
`"44'/397'/0'/0'/1'"`is near-cli's default path for ledger

**Comment by ilblackdragon** [comment]
@biluohc I'm not sure what you are referring to. Do you mean these paths should match?
