### ISSUE TITLE
keypath option doesn't work for local node

### ISSUE THREAD

**Issue by ailisp** [near/near-cli#766]
**Describe the bug**
Specify keyPath option to near-cli to interact with a local node doesn't work. Crash with suspicious `undefined` in path.

**To Reproduce**
Start the node by:
```
target/debug/neard --home /tmp/near-sandbox init
target/debug/neard --home /tmp/near-sandbox run
```
Then run near-cli:
```
➜  ~ export NEAR_ENV=local
➜  ~ near create-account status-message.testnet --initialBalance 10 --masterAccount testnet --keyPath /tmp/near-sandbox/testnet.json      
```
Error:
```
Loaded master account test.near key from /tmp/near-sandbox/testnet.json with public key = ed25519:68JMENiakg2bzAJFUzT7NQ7pnjg4B7YQMWpMkq5YnCoh
Saving key to 'undefined/local/status-message.testnet.json'
An error occured
Error: Can not sign transactions for account testnet on network local, no matching key pair found in InMemorySigner(MergeKeyStore(InMemoryKeyStore, MergeKeyStore(UnencryptedFileSystemKeyStore(/Users/bo/.near-credentials), UnencryptedFileSystemKeyStore(/Users/bo/neardev)))).
    at Account.signTransaction (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:92:19)
    at async /Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:117:34
    at async Object.exponentialBackoff [as default] (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async Account.signAndSendTransactionV2 (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:116:24)
    at async LocalAccountCreator.createAccount (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account_creator.js:24:9)
    at async Near.createAccount (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/near.js:69:9)
    at async createAccount (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/commands/create-account.js:137:26)
    at async Object.handler (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/utils/exit-on-error.js:52:9)
TypedError: Can not sign transactions for account testnet on network local, no matching key pair found in InMemorySigner(MergeKeyStore(InMemoryKeyStore, MergeKeyStore(UnencryptedFileSystemKeyStore(/Users/bo/.near-credentials), UnencryptedFileSystemKeyStore(/Users/bo/neardev)))).
    at Account.signTransaction (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:92:19)
    at async /Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:117:34
    at async Object.exponentialBackoff [as default] (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/exponential-backoff.js:7:24)
    at async Account.signAndSendTransactionV2 (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:116:24)
    at async LocalAccountCreator.createAccount (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account_creator.js:24:9)
    at async Near.createAccount (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/near.js:69:9)
    at async createAccount (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/commands/create-account.js:137:26)
    at async Object.handler (/Users/bo/.nvm/versions/node/v12.18.1/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'KeyNotFound',
  context: undefined
}
```

Note the suspicious undefined:
```
Saving key to 'undefined/local/status-message.testnet.json'
```

**Expected behavior**
It should take the specified json as master account's key and does not crash

**Additional context**
near-cli version 2.0.0

**Comment by ailisp** [comment]
Sorry I mis-spell the master account, so the issue is not key path option doesn't work. Just the error message not very friendly. This works:
```
near create-account status-message.test.near --initialBalance 10 --masterAccount test.near --keyPath /tmp/near-sandbox/validator-key.json
```
