### ISSUE TITLE
near view failed to parse JSON but same success use near call

### ISSUE THREAD

**Issue by ailisp** [near/near-cli#797]
near view:
 ```
 $ near view simple-state.abcdef.testnet get_status '

 {"account_id": "abcdef"} 

'
 View call: simple-state.abcdef.testnet.get_status(

 {"account_id": "abcdef"} 

)
 Log <span class="error">[simple-state.abcdef.testnet]</span>: get_status for account_id abcdef
 An error occured
 SyntaxError: Unexpected token in JSON at position 0
 at JSON.parse (<anonymous>)
 at parseJsonFromRawResponse (/home/bo/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:30:17)
 at Account.viewFunction (/home/bo/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:61)
 at processTicksAndRejections (internal/process/task_queues.js:93:5)
 at async exports.callViewFunction (/home/bo/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/index.js:75:48)
 at async Object.handler (/home/bo/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/utils/exit-on-error.js:52:9)
 SyntaxError: Unexpected token in JSON at position 0
 at JSON.parse (<anonymous>)
 at parseJsonFromRawResponse (/home/bo/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:30:17)
 at Account.viewFunction (/home/bo/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:366:61)
 at processTicksAndRejections (internal/process/task_queues.js:93:5)
 at async exports.callViewFunction (/home/bo/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/index.js:75:48)
 at async Object.handler (/home/bo/.nvm/versions/node/v14.16.1/lib/node_modules/near-cli/utils/exit-on-error.js:52:9)

```

near call (you'll need to replace --accountId with an account you have key to reproduce, this is a view method and doesn't matter which account is used to call):
 ```
 near call simple-state.abcdef.testnet get_status '

 {"account_id":"abcdef.testnet"} 

' --accountId abcdef.testnet
 Scheduling a call: simple-state.abcdef.testnet.get_status(

 {"account_id":"abcdef.testnet"} 

)
 Receipt: Dbm4raHGsYUyzA5aJKx5aodsNmBWL3n1xEaWTNwgZgUt
 Log <span class="error">[simple-state.abcdef.testnet]</span>: get_status for account_id abcdef.testnet
 Transaction Id C76C97Jqeztg61NxEr2iZarPJSjimGxp7X2VnwK4UQ2M
 To see the transaction in the transaction explorer, please open this url in your browser
 [https://explorer.testnet.near.org/transactions/C76C97Jqeztg61NxEr2iZarPJSjimGxp7X2VnwK4UQ2M](https://explorer.testnet.near.org/transactions/C76C97Jqeztg61NxEr2iZarPJSjimGxp7X2VnwK4UQ2M)
 '\x01\x05\x00\x00\x00hello'
 ```

The contract is near-sdk-rs example's status_message.wasm, deployed to `simple-state.abcdef.testnet` and the status was set by `near call simple-state.abcdef.testnet set_status --accountId abcdef.testnet '

 {"message":"hello"} 

'`

**Comment by ailisp** [comment]
near-cli is the latest 2.0.2
