### ISSUE TITLE
The account wouldn't have enough balance to cover storage 

### ISSUE THREAD

**Issue by vietnt11** [near/near-cli#912]
Hi Near,
I'm trying to deploy status message contract on testnet.
I'm getting the following error:
 ```
near deploy --wasmFile target/wasm32-unknown-unknown/release/key_value_storage.wasm --accountId hellocontract.nastmuratest.testnet 
Starting deployment. Account id: hellocontract.nastmuratest.testnet, node: https://rpc.testnet.near.org, helper: https://helper.testnet.near.org, file: target/wasm32-unknown-unknown/release/key_value_storage.wasm
Receipt: 
	Failure [hellocontract.nastmuratest.testnet]: Error: The account hellocontract.nastmuratest.testnet wouldn't have enough balance to cover storage, required to have 8065739611052772000000000 yoctoNEAR more
An error occured
Error: The account hellocontract.nastmuratest.testnet wouldn't have enough balance to cover storage, required to have 8065739611052772000000000 yoctoNEAR more
    at Object.parseResultError (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/rpc_errors.js:31:29)
    at Account.signAndSendTransactionV2 (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:160:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.deploy (/usr/local/lib/node_modules/near-cli/index.js:77:24)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9)
ServerTransactionError: The account hellocontract.nastmuratest.testnet wouldn't have enough balance to cover storage, required to have 8065739611052772000000000 yoctoNEAR more
    at Object.parseResultError (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/utils/rpc_errors.js:31:29)
    at Account.signAndSendTransactionV2 (/usr/local/lib/node_modules/near-cli/node_modules/near-api-js/lib/account.js:160:36)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exports.deploy (/usr/local/lib/node_modules/near-cli/index.js:77:24)
    at async Object.handler (/usr/local/lib/node_modules/near-cli/utils/exit-on-error.js:52:9) {
  type: 'LackBalanceForState',
  context: undefined,
  index: null,
  account_id: 'hellocontract.nastmuratest.testnet',
  amount: '8065739611052772000000000',
  kind: {
    account_id: 'hellocontract.nastmuratest.testnet',
    amount: '8065739611052772000000000'
  },
  transaction_outcome: {
    proof: [
      {
        hash: '8oMVbrvNPHEPCYQsyEVZBmEsvtpQTpgdHzAg5ue1BcGx',
        direction: 'Right'
      }
    ],
    block_hash: 'C4WRdy4x8gB2DR5Vxc95yQsVuGvygpcEEq5AXABz1B7w',
    id: 'FeNYRR1vfZJTf1eugg8CYaw2FkuRHQF8hzgEQTCiUc6a',
    outcome: {
      logs: [],
      receipt_ids: [ 'G34RDgoptnXg3FqKR23EhLas4rsKG58Gt6ZsouD13kBH' ],
      gas_burnt: 12598055263860,
      tokens_burnt: '1259805526386000000000',
      executor_id: 'hellocontract.nastmuratest.testnet',
      status: {
        SuccessReceiptId: 'G34RDgoptnXg3FqKR23EhLas4rsKG58Gt6ZsouD13kBH'
      },
      metadata: { version: 1, gas_profile: null }
    }
  }
}
 ```

**Comment by vietnt11** [comment]
I found the problem.
 At near deploy command , param --accountId , I pass wrong account (instead of passing accountID, I passed  the contractID).
 But if the error message like "Account ID not found" is more clear for everyone.

**Comment by volovyk-s** [comment]
@vietnt11 probably your account does not have enough balance to cover storage.
If you are sure, that this is a bug, we will need more information.
For example:
- near state <accountId>
- size of the wasm file

**Comment by volovyk-s** [comment]
Closing for now.
